/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author peace
 */
public class FlightSearch extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlightSearch.class.getName());

    /**
     * Creates new form FlightSearch
     */
    public FlightSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("   YATRAAIR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 20, 84, 37);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Search Flight Results");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 16, 175, 34);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Showing available flights based on your search criteria");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 54, 483, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("  Dashboard");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 70, 96, 36);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("  Search Flights");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 110, 96, 35);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("  My Bookings");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 150, 96, 35);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("  Check-In");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 190, 96, 39);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("   Profile");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 240, 96, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Customer Support");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 290, 117, 41);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Route");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(220, 170, 57, 20);

        jLabel11.setText("  KTM  -  PKR");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(210, 190, 80, 18);

        jLabel12.setText("DEPARTUREDATE");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(310, 170, 93, 16);

        jLabel13.setText("    28 Apr 2026");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(310, 190, 93, 18);

        jLabel14.setText("TRAVELERS");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(430, 170, 72, 16);

        jLabel15.setText("1 PESSENGER");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(420, 190, 72, 18);

        jLabel16.setText(" ---          FILTER RESULTS");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(580, 160, 176, 49);

        jLabel17.setText("YatraAir 101");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(230, 270, 80, 30);

        jLabel18.setText("  Standard Class");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jPanel1.add(jLabel18);
        jLabel18.setBounds(220, 300, 90, 20);

        jLabel19.setText("10:00 AM");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(320, 280, 70, 20);

        jLabel20.setText("KTM");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(330, 300, 43, 16);

        jLabel21.setText("--------------------");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(400, 290, 110, 16);

        jLabel22.setForeground(new java.awt.Color(51, 153, 255));
        jLabel22.setText("Direct Flight");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(410, 300, 80, 16);

        jLabel23.setText("1H 00 MIN");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(420, 280, 70, 20);

        jLabel24.setText("11:00 AM");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(520, 290, 60, 20);

        jLabel25.setText("PKR");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(530, 310, 21, 16);

        jLabel26.setText("TOTAL FEES");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(600, 280, 90, 16);

        jLabel27.setText("NPR 5,000");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(600, 300, 70, 20);

        jLabel28.setText(": VIEW DETAILS");
        jLabel28.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), null));
        jPanel1.add(jLabel28);
        jLabel28.setBounds(680, 290, 90, 20);

        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 250, 590, 100);

        jScrollPane2.setViewportView(jTextPane2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(200, 150, 590, 80);

        jScrollPane3.setViewportView(jTextPane3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(40, 50, 140, 290);

        jLabel29.setText("YatraAir 202");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(230, 390, 70, 20);

        jLabel30.setText("     Economy");
        jLabel30.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        jPanel1.add(jLabel30);
        jLabel30.setBounds(220, 410, 80, 20);

        jLabel31.setText("1:00 PM");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(320, 400, 43, 16);

        jLabel32.setText("KTM");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(330, 420, 40, 10);

        jLabel33.setText("-------------------");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(390, 400, 110, 10);

        jLabel34.setText("1H 00 MIN");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(400, 390, 70, 16);

        jLabel35.setForeground(new java.awt.Color(51, 153, 255));
        jLabel35.setText("Direct Flight");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(400, 410, 80, 16);

        jLabel36.setText("2:00 PM");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(520, 400, 50, 10);

        jLabel37.setText("PKR");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(530, 410, 21, 16);

        jLabel38.setText("TOTAL FEES");
        jPanel1.add(jLabel38);
        jLabel38.setBounds(600, 400, 80, 10);

        jLabel39.setText("NPR 4,500");
        jPanel1.add(jLabel39);
        jLabel39.setBounds(600, 410, 70, 20);

        jLabel40.setText(": VIEW DETAILS");
        jLabel40.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 102, 255), null));
        jPanel1.add(jLabel40);
        jLabel40.setBounds(680, 400, 90, 20);

        jScrollPane4.setViewportView(jTextPane4);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(200, 370, 590, 90);

        jLabel41.setText("YatraAir 303");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(230, 510, 70, 20);

        jLabel42.setText(" PremiumPlus");
        jLabel42.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), null));
        jPanel1.add(jLabel42);
        jLabel42.setBounds(220, 530, 90, 20);

        jLabel43.setText("4:00 PM");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(320, 510, 43, 16);

        jLabel44.setText("KTM");
        jPanel1.add(jLabel44);
        jLabel44.setBounds(330, 530, 25, 16);

        jLabel45.setText("--------------------");
        jPanel1.add(jLabel45);
        jLabel45.setBounds(380, 520, 110, 10);

        jLabel46.setText("1H 00 MIN");
        jPanel1.add(jLabel46);
        jLabel46.setBounds(400, 510, 70, 10);

        jLabel47.setForeground(new java.awt.Color(51, 153, 255));
        jLabel47.setText("Direct Flight");
        jPanel1.add(jLabel47);
        jLabel47.setBounds(400, 530, 80, 20);

        jLabel48.setText("5:00 PM");
        jPanel1.add(jLabel48);
        jLabel48.setBounds(510, 510, 42, 16);

        jLabel49.setText("PKR");
        jPanel1.add(jLabel49);
        jLabel49.setBounds(520, 530, 21, 16);

        jLabel50.setText("TOTAL FEES");
        jPanel1.add(jLabel50);
        jLabel50.setBounds(590, 510, 80, 16);

        jLabel51.setText("NPR 5,500");
        jPanel1.add(jLabel51);
        jLabel51.setBounds(590, 530, 60, 20);

        jLabel52.setText(": VIEW DETAILS");
        jLabel52.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 102, 255), null));
        jPanel1.add(jLabel52);
        jLabel52.setBounds(680, 520, 90, 20);

        jScrollPane5.setViewportView(jTextPane5);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(200, 490, 590, 90);

        jLabel53.setForeground(new java.awt.Color(255, 0, 51));
        jLabel53.setText("    Logout");
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel53);
        jLabel53.setBounds(100, 530, 70, 20);

        jScrollPane6.setViewportView(jTextPane6);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(100, 530, 70, 22);

        jScrollPane8.setViewportView(jTextPane8);

        jPanel1.add(jScrollPane8);
        jScrollPane8.setBounds(30, 20, 800, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void runFrame(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlightSearch().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane8;
    // End of variables declaration//GEN-END:variables
}
