/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 * FlightDetails class represents the GUI frame displaying details for the selected flight.
 * This includes class info, duration, baggage allowance, total fare summary, and cancellation policies.
 * 
 * @author peace
 */
public class FlightDetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlightDetails.class.getName());

    /**
     * Creates new form FlightDetails.
     * Initializes components generated by NetBeans GUI Builder.
     */
    public FlightDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        Dashboard = new javax.swing.JButton();
        SearchFlights = new javax.swing.JButton();
        MyBookings = new javax.swing.JButton();
        Profile = new javax.swing.JButton();
        CustomerSupport = new javax.swing.JButton();
        BookNewFlight = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        SaveForLater = new javax.swing.JButton();
        Proceed = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 0, 0, 0);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("YATRAAIR");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 50, 69, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText(": Back to Search Results");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 40, 210, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Yatra Air 101");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 110, 100, 20);

        jLabel9.setText("Economy Class : Non-Stop");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 130, 160, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("10:00 AM");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 110, 80, 20);

        jLabel11.setText("KTM");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 130, 25, 16);

        jLabel12.setText("------------------");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(510, 120, 90, 20);

        jLabel13.setText("1 hrs 00 min");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(520, 110, 70, 20);

        jLabel14.setForeground(new java.awt.Color(51, 153, 255));
        jLabel14.setText("Direct Flights");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(520, 130, 80, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("12:00 AM");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(610, 110, 70, 20);

        jLabel16.setText("PKR");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(620, 130, 30, 16);

        jLabel17.setText("TOTAL FARE");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(750, 110, 80, 20);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 255));
        jLabel18.setText("NPR 5,000 ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(740, 130, 100, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 255));
        jLabel19.setText("! Flight Information");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(380, 200, 180, 30);

        jLabel20.setText("AIRLINE");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(290, 240, 42, 16);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("  YatraAir");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(280, 260, 70, 20);

        jLabel22.setText("AIR CRAFT TYPE");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(270, 290, 90, 20);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("ATR 72");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(290, 310, 50, 20);

        jLabel24.setText("IN FLIGHT-MEAL");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(270, 330, 90, 20);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("INCLUDED");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(280, 350, 70, 20);

        jLabel26.setText("FLIGHT NO");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(510, 240, 60, 20);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("YS101");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(520, 260, 43, 16);

        jLabel28.setText("BAGGAGE ALLOWANCE");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(480, 290, 130, 20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("15 KG (CHECK-IN)");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(490, 310, 120, 20);

        jLabel30.setText("SEAT CONFIGURATION");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(480, 330, 130, 20);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("2-2 ECONOMY");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(500, 350, 100, 20);

        jLabel32.setText("-----------------------------------------------------------------------");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(270, 230, 360, 10);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("FARE SUMMARY");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(710, 220, 130, 30);

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("BEST FARE(1 ADULT)");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(670, 260, 110, 16);

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("NPR 4,200");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(790, 260, 60, 16);

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("TAXES & FEES");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(670, 280, 80, 20);

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("NPR 300");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(790, 280, 50, 16);

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("------------------------------------");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(670, 300, 180, 16);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("TOTAL PAY AVAILABLE");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(670, 320, 90, 30);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("NPR 5,000");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(760, 320, 90, 20);

        jTextPane4.setBackground(new java.awt.Color(0, 51, 153));
        jScrollPane4.setViewportView(jTextPane4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(660, 200, 200, 190);

        jLabel41.setText("CANCELLETION POLICY");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(660, 410, 140, 20);

        jLabel42.setText("Partially Refundable ");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(660, 430, 108, 20);

        jLabel43.setText("NPR 1,500");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(790, 430, 60, 20);

        jLabel44.setText("Free cancelletion within 24 hrs of ");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(660, 450, 180, 20);

        jLabel45.setText("booking. Thereafter standard ");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(660, 470, 160, 16);

        jLabel46.setText("airlines policy applied.");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(660, 490, 140, 16);

        jScrollPane5.setViewportView(jTextPane5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(630, 410, 220, 110);

        Dashboard.setText("    Dashboard");
        getContentPane().add(Dashboard);
        Dashboard.setBounds(70, 90, 110, 40);

        SearchFlights.setText("  Search Flights");
        getContentPane().add(SearchFlights);
        SearchFlights.setBounds(70, 140, 110, 40);

        MyBookings.setText("   My Bookings");
        getContentPane().add(MyBookings);
        MyBookings.setBounds(70, 190, 110, 40);

        Profile.setText("     Profile");
        getContentPane().add(Profile);
        Profile.setBounds(70, 240, 110, 40);

        CustomerSupport.setText("  Customer Support");
        getContentPane().add(CustomerSupport);
        CustomerSupport.setBounds(50, 290, 160, 50);

        BookNewFlight.setText("Book New Flight");
        getContentPane().add(BookNewFlight);
        BookNewFlight.setBounds(60, 520, 150, 40);

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setText("Logout");
        getContentPane().add(Logout);
        Logout.setBounds(80, 570, 90, 30);

        SaveForLater.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SaveForLater.setText("Save For Later                >");
        SaveForLater.addActionListener(this::SaveForLaterActionPerformed);
        getContentPane().add(SaveForLater);
        SaveForLater.setBounds(620, 570, 230, 30);

        Proceed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Proceed.setText("Proceed to passenger details >");
        getContentPane().add(Proceed);
        Proceed.setBounds(620, 530, 230, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPanel2);
        jPanel2.setBounds(250, 190, 380, 200);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(230, 90, 610, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveForLaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveForLaterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveForLaterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void runFrame(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlightDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookNewFlight;
    private javax.swing.JButton CustomerSupport;
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton Logout;
    private javax.swing.JButton MyBookings;
    private javax.swing.JButton Proceed;
    private javax.swing.JButton Profile;
    private javax.swing.JButton SaveForLater;
    private javax.swing.JButton SearchFlights;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    // End of variables declaration//GEN-END:variables
}
