/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 * PassengerDetails class represents the GUI frame where passengers input their
 * contact details and travel identification documents (e.g. Citizenship Card).
 * 
 * @author peace
 */
public class PassengerDetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PassengerDetails.class.getName());

    /**
     * Creates new form PassengerDetails.
     * Initializes components generated by NetBeans GUI Builder.
     */
    public PassengerDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yatraairheadling = new javax.swing.JLabel();
        backbottom = new javax.swing.JLabel();
        passengerdetailheadline = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        passengerinfo = new javax.swing.JLabel();
        nameinfo = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        emailinfo = new javax.swing.JLabel();
        phoneinfo = new javax.swing.JLabel();
        identificationinfo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        SearchFlights = new javax.swing.JButton();
        mybookings = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        CustomerSupport = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        CitizenshipCard = new javax.swing.JButton();
        idnumber = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        Seat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        yatraairheadling.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        yatraairheadling.setText("YATRAAIR");
        jPanel1.add(yatraairheadling);
        yatraairheadling.setBounds(64, 57, 91, 25);

        backbottom.setForeground(new java.awt.Color(0, 153, 255));
        backbottom.setText("<--Back to flights Details");
        jPanel1.add(backbottom);
        backbottom.setBounds(220, 60, 150, 30);

        passengerdetailheadline.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passengerdetailheadline.setForeground(new java.awt.Color(0, 0, 255));
        passengerdetailheadline.setText("Passenger Details");
        jPanel1.add(passengerdetailheadline);
        passengerdetailheadline.setBounds(220, 90, 180, 30);

        info.setText("Complete the information below to finaliize your bookings");
        jPanel1.add(info);
        info.setBounds(220, 120, 320, 30);

        passengerinfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passengerinfo.setForeground(new java.awt.Color(0, 102, 204));
        passengerinfo.setText("Passenger Information");
        jPanel1.add(passengerinfo);
        passengerinfo.setBounds(230, 160, 170, 40);

        nameinfo.setText("Full Name (AS PER ID)");
        jPanel1.add(nameinfo);
        nameinfo.setBounds(230, 200, 130, 20);

        name.setText("e.g. Parbat Thapa");
        name.addActionListener(this::nameActionPerformed);
        jPanel1.add(name);
        name.setBounds(230, 220, 510, 30);

        emailinfo.setText("Email Address");
        jPanel1.add(emailinfo);
        emailinfo.setBounds(230, 260, 80, 20);

        phoneinfo.setText("Phone Number");
        jPanel1.add(phoneinfo);
        phoneinfo.setBounds(500, 260, 90, 20);

        identificationinfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        identificationinfo.setForeground(new java.awt.Color(0, 102, 204));
        identificationinfo.setText("Identification");
        jPanel1.add(identificationinfo);
        identificationinfo.setBounds(230, 360, 150, 25);

        jLabel16.setText("ID TYPE");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(230, 390, 50, 20);

        jLabel17.setText("ID NUMBER");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(510, 390, 70, 20);

        jLabel18.setForeground(new java.awt.Color(0, 102, 204));
        jLabel18.setText("  !  Please ensure the ID information matches documents you will carry during travels.");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(230, 440, 510, 30);

        jLabel19.setForeground(new java.awt.Color(0, 102, 204));
        jLabel19.setText("Incorrect information may lead to boarding refusal");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(240, 460, 300, 20);

        Dashboard.setText("    Dashboard");
        jPanel1.add(Dashboard);
        Dashboard.setBounds(60, 100, 110, 40);

        SearchFlights.setText("  Search Flights");
        jPanel1.add(SearchFlights);
        SearchFlights.setBounds(60, 150, 110, 40);

        mybookings.setText("   My Bookings");
        jPanel1.add(mybookings);
        mybookings.setBounds(60, 200, 110, 40);

        profile.setText("     Profile");
        jPanel1.add(profile);
        profile.setBounds(60, 250, 110, 40);

        CustomerSupport.setText("  Customer Support");
        jPanel1.add(CustomerSupport);
        CustomerSupport.setBounds(40, 300, 160, 40);

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setText("Logout");
        jPanel1.add(Logout);
        Logout.setBounds(70, 500, 100, 40);

        CitizenshipCard.setText("Citizenship Card                          ");
        jPanel1.add(CitizenshipCard);
        CitizenshipCard.setBounds(220, 410, 190, 30);

        idnumber.setText("Citizenship Number ");
        jPanel1.add(idnumber);
        idnumber.setBounds(500, 410, 150, 30);

        email.setText("parbat@example .com");
        jPanel1.add(email);
        email.setBounds(230, 290, 160, 30);

        number.setText("97XXXXXXXX");
        jPanel1.add(number);
        number.setBounds(500, 290, 160, 30);

        Seat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Seat.setText("  Select Seat  -->");
        jPanel1.add(Seat);
        Seat.setBounds(220, 500, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void runFrame(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PassengerDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CitizenshipCard;
    private javax.swing.JButton CustomerSupport;
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton Logout;
    private javax.swing.JButton SearchFlights;
    private javax.swing.JButton Seat;
    private javax.swing.JLabel backbottom;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailinfo;
    private javax.swing.JLabel identificationinfo;
    private javax.swing.JButton idnumber;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mybookings;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameinfo;
    private javax.swing.JTextField number;
    private javax.swing.JLabel passengerdetailheadline;
    private javax.swing.JLabel passengerinfo;
    private javax.swing.JLabel phoneinfo;
    private javax.swing.JButton profile;
    private javax.swing.JLabel yatraairheadling;
    // End of variables declaration//GEN-END:variables
}
