/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author peace
 */
public class PassengerDetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PassengerDetails.class.getName());

    /**
     * Creates new form PassengerDetails
     */
    public PassengerDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("YATRAAIR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(64, 57, 91, 25);

        jLabel2.setText("    Dashboard");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(64, 100, 91, 31);

        jLabel3.setText("  Search Flights");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(64, 137, 91, 33);

        jLabel4.setText("   My Bookings");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(64, 176, 91, 33);

        jLabel5.setText("     Profile");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(64, 215, 91, 34);

        jLabel6.setText("  Customer Support");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(52, 261, 119, 34);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Logout");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(84, 532, 47, 20);

        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("<--Back to flights Details");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 60, 150, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Passenger Details");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(220, 90, 180, 30);

        jLabel10.setText("Complete the information below to finaliize your bookings");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(220, 120, 320, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setText("Passenger Information");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(230, 160, 170, 40);

        jLabel12.setText("Full Name (AS PER ID)");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(230, 200, 130, 20);

        jTextField1.setText("e.g. Parbat Thapa");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(230, 220, 510, 30);

        jLabel13.setText("Email Address");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(230, 260, 80, 20);

        jLabel14.setText("Phone Number");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(500, 260, 90, 20);

        jTextField2.setText("parbat@example .com");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(230, 280, 190, 30);

        jTextField3.setText("97XXXXXXXX");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(500, 280, 240, 30);

        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(210, 160, 560, 180);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("Identification");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(230, 360, 150, 25);

        jLabel16.setText("ID TYPE");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(230, 390, 50, 20);

        jTextField4.setText("Citizenship Card                          v");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(230, 410, 190, 30);

        jLabel17.setText("ID NUMBER");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(510, 390, 70, 20);

        jTextField5.setText("Citizenship Number ");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(510, 410, 230, 30);

        jLabel18.setForeground(new java.awt.Color(0, 102, 204));
        jLabel18.setText("  !  Please ensure the ID information matches documents you will carry during travels.");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(230, 440, 510, 30);

        jLabel19.setForeground(new java.awt.Color(0, 102, 204));
        jLabel19.setText("Incorrect information may lead to boarding refusal");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(240, 460, 300, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("  Select Seat  -->");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(240, 520, 150, 40);

        jTextPane2.setBackground(new java.awt.Color(0, 102, 204));
        jScrollPane2.setViewportView(jTextPane2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(220, 520, 200, 40);

        jScrollPane3.setViewportView(jTextPane3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(30, 30, 830, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void runFrame(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PassengerDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
